# Generated by Django 3.2.9 on 2021-12-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20211205_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله وِیژه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشرشده'), ('i', 'درحال بررسی'), ('b', 'برگشت داده شده')], max_length=10, verbose_name='وضعیت'),
        ),
    ]
