# Generated by Django 3.2.9 on 2021-12-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20211223_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه'),
        ),
    ]
