# Generated by Django 3.2.9 on 2022-02-04 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_slide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slide',
        ),
    ]
