# Generated by Django 3.2.9 on 2022-03-01 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_delete_slide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-publish'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
    ]
