# Generated by Django 3.2.9 on 2022-03-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.ManyToManyField(to='blog.NewsletterUser', verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشرشده')], max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='موضوع'),
        ),
    ]
