# Generated by Django 3.2.9 on 2022-03-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20220322_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
